export const SIGN_IN_WITH_PROVIDER = 'SIGN_IN_WITH_PROVIDER';
export const SIGN_IN_WITH_EMAIL = 'SIGN_IN_WITH_EMAIL'
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';

export const SIGN_IN_FULFILLED = 'SIGN_IN_FULFILLED';
export const SIGN_OUT_FULFILLED = 'SIGN_OUT_FULFILLED';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_FAILED = 'REGISTER_FAILED';